### PR TITLE
Remove the multi-branch plugin that has been DEPRECATED

### PR DESCRIPTION
**Pull request by sfransen**
the plugin has been DEPRECATED

### CODE REVIEW

**Comment by sfransen** [comment]
This needs to be done. Why include a plugin that is DEPRECATED

**Comment by jonathannaguin** [comment]
Can this be merged please? It's really annoying to see the new warning banner complaning about the multi-branch plugin.

**Comment by vhaidamaka** [comment]
Do you have plans to merge this PR? Because the warning banner cannot be dismissed and as @jonathannaguin mentioned this is really annoying.

**Comment by rob-spoor** [comment]
Why is there no action after almost 4 years? We can't remove the last deprecated plugin because this plugin depends on it, and we still use this plugin.

**Comment by dawidmalina** [comment]
Thanks for your contribution. Keep in mind that code base is also quite obsolete and it might take a while to prepare new release.

**Pull request merged**
