### PR TITLE
Add ability to hide environment variables values

### PR DESCRIPTION
**Pull request by dawidmalina**
- Add configurable option that allows hide environment variables values
- Add needed help messages
- Disable -x in bash scripts

### CODE REVIEW

**Comment by dawidmalina** [comment]
@jdolitsky can you check whether this change meets your expectations

**Comment by jdolitsky** [comment]
@dawidmalina looks good from what I can tell!
Going to try to build and test in a few hours, and will let you know

**Comment by jdolitsky** [comment]
@dawidmalina This works perfectly. Thanks so much.

**Comment by jdolitsky** [comment]
@dawidmalina I saw that this is in the official 1.2.3 release... thank you!!!

**Pull request merged**
